### ISSUE TITLE
Cool ;)

### ISSUE THREAD

**Issue by wpexplorer** [joomlaworks/fill-it-up-for-wordpress#2]
This looks pretty cool. The only thing that worries me (I haven't looked at the code yet) is copyrighted images I see on CSSIgniter http://www.cssigniter.com/playground/ at least 1 image that for sure they wouldn't have the permissions to use.

That said, I did read the part about custom dummy content, now this is cool! Not sure if it does it already, but if can integrate with Amazon s3 or Dropbox - hells ya!

Will keep an eye out on this project, definitely cool.

Feel free to reach out to us in the future on twitter and keep us in the loop!
- AJ

**Comment by fevangelou** [comment]
Thanks AJ :)

If you could let me know on that image, I'd be happy to notify CSSIgniter to remove it. Perhaps it's part of our demo definitions file and we should remove it as well.

As for how it works, since the point is to just use a .json file to define basic categories, media and link (to retrieve) zip file locations, then yes, it can be hosted anywhere (even on GitHub pages).

What would be really cool is to have prominent members and companies in the WP community build their own packs to share :)

**Comment by wpexplorer** [comment]
Pretty sure I saw a photo of Brad Pitt, but I could be wrong...

Anyway I hadn't looked into the plugin too much I just assumed it auto grabbed images from places like unsplash and pixabay. I will definitely be taking a closer look for sure and already forked it.

But ya would be cool to work on an "add-ons" panel so users can download new "packs" via the dashboard. So 3rd party authors can provided "packs" to share.

By the way I have been looking for a good developer to help in the development in a demo importer for my Total theme (I would love to do it but so dam swamped atm). It would basically just pull from a github repository (xml file, widgets.txt, sliders.zip) and import the content for the user. Not sure if you or someone you know would be interested in the project. But thought it couldn't hurt asking since this plugin is fairly similar in a sense. Please let me know!
- AJ
